---
title: "My interactive Rmd"
author: "Anna Talken"
date: "1/26/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r flippers, echo = FALSE}

inputPanel(
  
  #creating a drop down menu
  selectInput(inputId = "pick_spp",
              label = "Pick your penguin species",
              choices = c("Adélie" = "Adelie", "Chinstrap", "Gentoo"), selected = "Gentoo"), #You can dictate what the name will appear as to the user (as in Adelie)
 
  #creating a sliding bar widget 
 sliderInput(inputId = "pt_size",
             label = "Set your point size",
             min = 1,
             max = 10,
             step = 0.5,
             value = 5) 

)
#creating a reactive data frame
penguin_set <- reactive({
  penguins %>% 
    filter(species == input$pick_spp)
})
#creating a plot, must include open and closed parentheses at the end of the data set that you call into the ggplot
renderPlot({
  ggplot(data = penguin_set(), aes(x = flipper_length_mm, y = body_mass_g)) +
    geom_point(size = input$pt_size) #point size changes based on the sliding bar that I created above
  
})

```

